# Generated by Django 4.1.7 on 2025-09-02 12:30:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_change_conversation_to_integer'),
    ]

    operations = [
        # Удаляем неправильный foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_conversation_id_5ef638db_fk_conversations_id;",
            reverse_sql="-- Не можем восстановить constraint, так как он был неправильным"
        ),
        
        # Добавляем правильный индекс для conversation_id
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS messages_conversation_id_idx ON messages(conversation_id);",
            reverse_sql="DROP INDEX IF EXISTS messages_conversation_id_idx;"
        ),
    ]
