# Generated by Django 4.1.7 on 2025-09-02 12:30:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_change_conversation_to_integer'),
    ]

    def drop_bad_fk(apps, schema_editor):
        # Выполняем удаление CONSTRAINT только в PostgreSQL. SQLite не поддерживает DROP CONSTRAINT.
        if getattr(schema_editor.connection, 'vendor', None) != 'postgresql':
            return
        schema_editor.execute(
            "ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_conversation_id_5ef638db_fk_conversations_id;"
        )

    operations = [
        migrations.RunPython(drop_bad_fk, reverse_code=migrations.RunPython.noop),
    ]
